apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus-service 
          image: event-bus-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30000
          env:
            - name: ENV 
              value: "local"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30000"
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: mongo-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: NOTE_EVENT_ROUTE 
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: note-url
            - name: NOTE_EVENT_PORT
              value: "30010"
            - name: BEHAVE_EVENT_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: behave-url
            - name: BEHAVE_EVENT_PORT
              value: "30020"
            - name: QUERY_EVENT_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: query-url
            - name: QUERY_EVENT_PORT
              value: "30030"
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  type: NodePort
  selector:
    app: event-bus 
  ports:
    - protocol: TCP 
      port: 30000
      targetPort: 30000
      nodePort: 30000
